name: tf apply prod

on:
  push:
    branches: [ "master" ]
    paths:
      - "envs/prod/**"
      - "modules/**"
      - ".github/workflows/tf-apply-prod.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: envs/prod
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_PROD }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Terraform init
        run: terraform init -input=false
      - name: Terraform apply
        run: terraform apply -auto-approve -input=false